"""Staff schema

Revision ID: 086ecfbe9265
Revises: d2b685d8ee09
Create Date: 2024-01-08 11:38:35.420956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086ecfbe9265'
down_revision = 'd2b685d8ee09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_staff')
    # ### end Alembic commands ###
